config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :pokemons, only: [:index, :show, :new, :create, :destroy]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/pokemon.rb
class Pokemon < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/pokemons_controller.rb
class PokemonsController < ApplicationController
  before_action :find_pokemon, only: [:show, :destroy]

  def index
    @pokemons = Pokemon.all
  end

  def show
  end

  def new
    @pokemon = Pokemon.new
  end

  def create
    @pokemon = Pokemon.new(pokemon_params)
  end

  def destroy
  end

  private

  def pokemon_params
    params.require(:pokemon).permit(:name, :picture, :ability)
  end

  def find_pokemon
    @pokemon = Pokemon.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pokemons_helper.rb
module PokemonsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>PokemonBook</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/pokemons/index.html.erb
<div class="wrapper">
    <h1>All our pokemons (<%= @pokemons.length %>)</h1>
    <div class="cards">
        <% @pokemons.each do |pokemon| %>
        <div class="card-category" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url('<%= pokemon.picture %>')">
          <%= link_to pokemon.name, pokemon_path(pokemon) %>
        </div>
        <% end %>
    </div>
</div>

app/views/pokemons/show.html.erb
<div class="wrapper">
  <h1><%= @pokemon.name %></h1>
  <div class="cards">
    <div class="card-category" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url('<%= pokemon.picture %>')">
      <%= pokemon.name %>
    </div>
    <%= pokemon.ability %>
  </div>
  <%= link_to "Go Back", pokemons_path %>
</div>